apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: dotnet-sdk
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.19"
    tekton.dev/tags: dotnet, workspace
    tekton.dev/displayName: ".NET SDK"
spec:
  description: >-
    dotnet-sdk task runs a user-specified script that can use the .NET SDK.
  workspaces:
    - name: source
      mountPath: /workspace/source
      description: >-
        An optional workspace that allows to provide source code.
      optional: true
    - name: dockerconfig
      description: >-
        An optional workspace that allows providing a .docker/config.json file to access the container registry.
        The file should be placed at the root of the Workspace with name config.json or .dockerconfigjson.
      optional: true
    - name: dotnetconfig
      description: >-
        An optional workspace that allows providing common configuration for .NET Tekton tasks.
        If a 'setup' file is present, its contents get executed before running the script.
        If a 'Build.props' file is present, it will be loaded by the .NET SDK through CustomBeforeDirectoryBuildProps.
      optional: true
  params:
    - name: SCRIPT
      description: The OpenShift CLI arguments to run
      type: string
      default: |
          set -x

          PROJECT=app.proj IMAGE_NAME=app-image
          dotnet publish /t:PublishContainer /p:UseDotnetImageStreamBaseImages=true /p:ContainerRegistry=${OpenShiftInternalRegistry} "/p:ContainerRepository=${OpenShiftCurrentNamespace}/${IMAGE_NAME}" "${PROJECT}"
    - name: SDK_VERSION
      default: latest
      description: Tag of .NET SDK imagestream.
      type: string
    - name: DOTNET_NAMESPACE
      description: Namespace of the .NET imagestreams. Set to '$(context.taskRun.namespace)' to use the pipeline namespace.
      default: openshift
      type: string
    - name: ENV_VARS
      type: array
      description: Environment variables.
      default: []
  steps:
    - name: dotnet
      image: image-registry.openshift-image-registry.svc:5000/$(params.DOTNET_NAMESPACE)/dotnet:$(params.SDK_VERSION)
      args:
        - "--env-vars"
        - "$(params.ENV_VARS[*])"
      env:
      - name: OpenShiftInternalRegistry
        value: "image-registry.openshift-image-registry.svc:5000"
      - name: OpenShiftDotnetNamespace
        value: $(params.DOTNET_NAMESPACE)
      - name: OpenShiftCurrentNamespace
        value: $(context.taskRun.namespace)
      - name: RunningInTekton
        value: "true"
      - name: DOTNETCONFIG_DIRECTORY_BOUND
        value: $(workspaces.dotnetconfig.bound)
      - name: DOTNETCONFIG_DIRECTORY_PATH
        value: $(workspaces.dotnetconfig.path)
      script: |
        #!/usr/bin/env bash

        set -euo pipefail

        parsing_flag=""
        for arg in "$@"; do
            if [[ "$arg" == "--env-vars" ]]; then
                parsing_flag="env-vars"
            elif [[ "$parsing_flag" == "env-vars" ]]; then
                export "$arg"
            fi
        done

        if [[ "$(workspaces.dockerconfig.bound)" == "true" ]]; then
          mkdir -p ~/.config/containers
          [[ -f "$(workspaces.dockerconfig.path)/config.json" ]] && ln -s "$(workspaces.dockerconfig.path)/config.json" ~/.config/containers/auth.json
          [[ -f "$(workspaces.dockerconfig.path)/.dockerconfigjson" ]] && ln -s "$(workspaces.dockerconfig.path)/.dockerconfigjson" ~/.config/containers/auth.json
        fi

        mkdir -p ~/src
        if [[ "$(workspaces.source.bound)" == "true" ]]; then
          cp -a "$(workspaces.source.path)/." ~/src
        fi
        cd ~/src

        if [[ "${DOTNETCONFIG_DIRECTORY_BOUND}" == "true" ]] && [[ -f "${DOTNETCONFIG_DIRECTORY_PATH}/setup" ]]; then
          source "${DOTNETCONFIG_DIRECTORY_PATH}/setup"
        fi

        cat >/tmp/UseDotnetImageStreamBaseImages.targets <<'EOF'
        <Project>
          <Target Name="ComputeOpenShiftContainerBaseImage" BeforeTargets="ComputeContainerBaseImage">

            <Error Condition="'$(OpenShiftDotnetNamespace)' == ''" Text="'OpenShiftDotnetNamespace' is not set." />

            <PropertyGroup>
              <OpenShiftInternalRegistry Condition="'$(OpenShiftInternalRegistry)' == ''">image-registry.openshift-image-registry.svc:5000</OpenShiftInternalRegistry>

              <!-- Pick the proper base image from the OpenShiftDotnetNamespace namespace. -->
              <ContainerBaseImage>$(OpenShiftInternalRegistry)/$(OpenShiftDotnetNamespace)/dotnet-runtime:$(_TargetFrameworkVersionWithoutV)</ContainerBaseImage>
            </PropertyGroup>
          </Target>
        </Project>
        EOF

        export CustomBeforeDirectoryBuildProps="/tmp/CustomBeforeDirectoryBuildProps.props"
        cat >"${CustomBeforeDirectoryBuildProps}" <<'EOF'
        <Project>
          <Import Project="$(DOTNETCONFIG_DIRECTORY_PATH)/Build.props" Condition="'$(DOTNETCONFIG_DIRECTORY_BOUND)' == 'true' And Exists('$(DOTNETCONFIG_DIRECTORY_PATH)/Build.props')" />
          <Import Project="/tmp/UseDotnetImageStreamBaseImages.targets" Condition="'$(UseDotnetImageStreamBaseImages)' == 'true'"/>
        </Project>
        EOF

        $(params.SCRIPT)
